package org.ferdev.contactapp.repository;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.amazonaws.services.dynamodbv2.document.Table;
import com.amazonaws.services.dynamodbv2.document.spec.GetItemSpec;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.AttributeValueUpdate;
import com.amazonaws.services.dynamodbv2.model.PutItemRequest;
import com.amazonaws.services.dynamodbv2.model.UpdateItemRequest;
import org.ferdev.contactapp.model.Contact;
import org.ferdev.contactapp.model.ContactRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.UUID;

public class DbManager {

    private static Logger logger = LoggerFactory.getLogger("jsonLogger");
    private final String DYNAMODB_TABLE_NAME = "Contacts-FernandoAvila";
    private final Regions REGION = Regions.US_EAST_1;
    private AmazonDynamoDB amazonDynamoDB = AmazonDynamoDBClientBuilder.standard().withRegion(REGION).build();

    public Contact saveContact(ContactRequest contactRequest) {
        String autoGeneratedId = UUID.randomUUID().toString();

        amazonDynamoDB.putItem(new PutItemRequest()
                .withTableName(DYNAMODB_TABLE_NAME)
                .addItemEntry("id", new AttributeValue(autoGeneratedId))
                .addItemEntry("firstName", new AttributeValue(contactRequest.getFirstName()))
                .addItemEntry("lastName", new AttributeValue(contactRequest.getLastName()))
                .addItemEntry("status", new AttributeValue("CREATED")));

        return this.getContactById(autoGeneratedId);
    }

    public Contact getContactById(String contactId) {
        DynamoDB dynamoDB = new DynamoDB(amazonDynamoDB);
        Table table = dynamoDB.getTable(DYNAMODB_TABLE_NAME);
        GetItemSpec getItemSpec = new GetItemSpec().withPrimaryKey("id", contactId);

        Item contactItem = table.getItem(getItemSpec);
        if (contactItem != null) {

            Contact contact = new Contact();
            contact.setId(contactItem.getString("id"));
            contact.setFirstName(contactItem.getString("firstName"));
            contact.setLastName(contactItem.getString("lastName"));
            contact.setStatus(contactItem.getString("status"));

            return contact;
        } else {
            return null;
        }
    }

    public void updateContactById(String contactId) {
        logger.info("DbManager UpdateContactById");
        AttributeValue statusValue = new AttributeValue().withS("PROCESSED");

        AttributeValueUpdate update = new AttributeValueUpdate()
                .withAction("PUT")
                .withValue(statusValue);

        logger.info("DbManager UpdateContactById - To update");
        UpdateItemRequest request = new UpdateItemRequest()
                .withTableName("Contacts-FernandoAvila")
                .addKeyEntry("id", new AttributeValue(contactId))
                .addAttributeUpdatesEntry("status", update);

        logger.info("DbManager UpdateContactById - Updated");

        amazonDynamoDB.updateItem(request);
    }
}
